[project]
name = "large-scale-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "baml-py>=0.214.0",
    "load-dotenv>=0.1.0",
    "numpy>=2.3.5",
    "openai>=2.9.0",
]
